"use client";

import { FileSpreadsheet, Download } from "lucide-react";
import { LogInspectionResponse } from "@/types/inspection.types";
import { Statistics } from "@/types/statistics.types";

interface ExportSectionProps {
  inspections?: LogInspectionResponse[];
  statistics?: Statistics;
}

export function ExportSection({
  inspections = [],
  statistics,
}: ExportSectionProps) {
  const handleExportCSV = () => {
    if (!inspections || inspections.length === 0) {
      alert("No inspections to export");
      return;
    }

    // Create CSV headers
    const headers = [
      "Asset ID",
      "Type",
      "Date",
      "Performed By",
      "Notes",
      "Status",
    ];

    // Create CSV rows
    const rows = inspections.map((item) => [
      item.inspection.assetId,
      item.inspection.type,
      new Date(item.inspection.inspectionDate).toLocaleDateString(),
      item.inspection.performedBy,
      item.inspection.notes || "",
      item.asset.status,
    ]);

    // Combine headers and rows
    const csvContent = [
      headers.join(","),
      ...rows.map((row) =>
        row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","),
      ),
    ].join("\n");

    // Create blob and download
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);

    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `inspections_${new Date().toISOString().split("T")[0]}.csv`,
    );
    link.style.visibility = "hidden";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportReport = () => {
    if (!inspections || inspections.length === 0) {
      alert("No inspections to generate report");
      return;
    }

    // Create a simple HTML report
    const reportContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Inspection Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #111827; border-bottom: 2px solid #E5E7EB; padding-bottom: 10px; }
    .summary { background: #F6F7FA; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .summary-item { display: flex; justify-content: space-between; margin: 10px 0; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #E5E7EB; }
    th { background: #F6F7FA; font-weight: 600; color: #6B7280; }
    .status-green { color: #10B981; }
    .status-yellow { color: #F59E0B; }
    .status-red { color: #EF4444; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; color: #6B7280; font-size: 14px; }
  </style>
</head>
<body>
  <h1>AmanTrack Inspection Report</h1>
  <p>Generated on: ${new Date().toLocaleString()}</p>
  
  ${
    statistics
      ? `
  <div class="summary">
    <h2>Summary Statistics</h2>
    <div class="summary-item">
      <span>Total Assets:</span>
      <strong>${statistics.total}</strong>
    </div>
    <div class="summary-item">
      <span>Valid Assets:</span>
      <strong class="status-green">${statistics.valid}</strong>
    </div>
    <div class="summary-item">
      <span>Expired Assets:</span>
      <strong class="status-red">${statistics.expired}</strong>
    </div>
    <div class="summary-item">
      <span>Compliance Rate:</span>
      <strong>${statistics.compliancePercentage.toFixed(1)}%</strong>
    </div>
  </div>
  `
      : ""
  }
  
  <h2>Inspections (${inspections.length})</h2>
  <table>
    <thead>
      <tr>
        <th>Asset ID</th>
        <th>Type</th>
        <th>Date</th>
        <th>Performed By</th>
        <th>Status</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${inspections
        .map(
          (item) => `
        <tr>
          <td>${item.inspection.assetId}</td>
          <td><strong>${item.inspection.type}</strong></td>
          <td>${new Date(item.inspection.inspectionDate).toLocaleDateString()}</td>
          <td>${item.inspection.performedBy}</td>
          <td class="status-${item.asset.status.toLowerCase()}">${item.asset.status}</td>
          <td>${item.inspection.notes || "-"}</td>
        </tr>
      `,
        )
        .join("")}
    </tbody>
  </table>
  
  <div class="footer">
    <p>This report was generated by AmanTrack - Asset Management System</p>
  </div>
</body>
</html>
    `;

    // Create blob and download
    const blob = new Blob([reportContent], {
      type: "text/html;charset=utf-8;",
    });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);

    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `inspection_report_${new Date().toISOString().split("T")[0]}.html`,
    );
    link.style.visibility = "hidden";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="bg-white dark:bg-[#1B1F28] border border-[#E5E7EB] dark:border-[#2D3340] rounded-lg shadow-lg dark:shadow-none p-4 sm:p-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg sm:text-xl font-semibold text-[#111827] dark:text-[#E4E6EB] flex items-center gap-2">
            <Download className="w-5 h-5 sm:w-6 sm:h-6" />
            Export & Reports
          </h2>
          <p className="text-xs sm:text-sm text-[#6B7280] dark:text-[#9CA3AF] mt-1">
            Download inspection data and generate reports
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 w-full sm:w-auto">
          <button
            onClick={handleExportCSV}
            disabled={!inspections || inspections.length === 0}
            className="
              cursor-pointer
              inline-flex items-center justify-center gap-2
              px-4 py-2.5
              bg-green-600 hover:bg-green-700
              dark:bg-green-600 dark:hover:bg-green-700
              text-white font-medium text-sm
              rounded-lg
              transition-colors
              disabled:opacity-50 disabled:cursor-not-allowed
              w-full sm:w-auto
            "
          >
            <FileSpreadsheet className="w-4 h-4" />
            Export CSV
          </button>

          <button
            onClick={handleExportReport}
            disabled={!inspections || inspections.length === 0}
            className="
              cursor-pointer
              inline-flex items-center justify-center gap-2
              px-4 py-2.5
              bg-blue-600 hover:bg-blue-700
              dark:bg-blue-600 dark:hover:bg-blue-700
              text-white font-medium text-sm
              rounded-lg
              transition-colors
              disabled:opacity-50 disabled:cursor-not-allowed
              w-full sm:w-auto
            "
          >
            <Download className="w-4 h-4" />
            Generate Report
          </button>
        </div>
      </div>
    </div>
  );
}
